version: '3.8'
services:

  project:
    build: ./Project
    container_name: project
    ports:
      - "8080:8080"
    env_file: 
      - ./project.env
    environment: 
      - DATABASE_DOMAIN=postgres
    links:
      - postgres

  postgres:
    image: 'postgres'
    ports:
      - "5433:5432"
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=SimpleApp
    volumes: 
      - postgresDB:/var/lib/postgresql/data
    
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - project


volumes:
  postgresDB: